### ISSUE TITLE
Reading config from secrets.yml?

### ISSUE THREAD

**Issue by jonbuda** [kjohnston/s3_relay#19]
As folks move to Rails 5.1 with encrypted secrets it might make sense to allow the config to be set from `Rails.application.secrets...` or have a way to set configuration in an initializer to be a bit more flexible? Happy to issue to a PR if you're open to it.

**Comment by kjohnston** [comment]
Rails 5.2 is [deprecating secrets](http://weblog.rubyonrails.org/2017/11/27/Rails-5-2-Active-Storage-Redis-Cache-Store-HTTP2-Early-Hints-Credentials/) in favor of [Credentials](https://github.com/rails/rails/pull/30067) which currently assumes support for only one environment is needed... so it seems to be needing further evolution before it stabilizes.

My recommendation is to use [dotenv](https://github.com/bkeepers/dotenv) to read from (per-environment) environment variables.
