### ISSUE TITLE
S3 endpoint template doesn't work with "us-east-1" region 

### ISSUE THREAD

**Issue by artemf** [kjohnston/s3_relay#25]
The following AWS S3 endpoint template in `S3Relay::Base#endpoint`:
```
"https://#{bucket}.s3-#{region}.amazonaws.com"
```

Doesn't work with the (most widespread) `us-east-1` region, as [these are the only valid enpoints](https://docs.aws.amazon.com/general/latest/gr/rande.html) for the region:
- s3.amazonaws.com
- s3.us-east-1.amazonaws.com
- s3-external-1.amazonaws.com

I suggest to change the template to `"https://#{bucket}.s3.#{region}.amazonaws.com"` (dot instead of dash), as it seems to be the only template working with all the regions.

Thanks!

**Comment by kjohnston** [comment]
This is addressed by #26, which uses AWS' latest recommendation: `"https://s3.#{region}.amazonaws.com/#{bucket}"`.
