### ISSUE TITLE
[tutorial] Adding AWS credentials

### ISSUE THREAD

**Issue by famousky** [kjohnston/s3_relay#4]
Tried few methods known to me but none of them worked. Where to put AWS credentials and how Relay will hook them up?

**Comment by famousky** [comment]
Answer:

1. Create **config/local_env.yml** and put inside:

S3_RELAY_ACCESS_KEY_ID: XXXXXXXXXXXX
S3_RELAY_SECRET_ACCESS_KEY: YYYYYYYYYYYYYYYYY/ZZZZZ
S3_RELAY_BUCKET: YOURBUCKET
S3_RELAY_REGION: YOURREGION
S3_RELAY_ACL: private

2. Add to .gitignore config/local_env.yml so you never commit it!



3. Add to **config/application.rb** inside _class Application_ :

module YOURAWESOMEAPP
  class Application < Rails::Application
 ...
    config.before_configuration do
      env_file = File.join(Rails.root, 'config', 'local_env.yml')
      YAML.load(File.open(env_file)).each do |key, value|
        ENV[key.to_s] = value
      end if File.exists?(env_file)
    end
....
  end
end

**Comment by kjohnston** [comment]
Thanks for posting this detail here.  There is a Rails convention for this ([secrets.yml](http://guides.rubyonrails.org/4_1_release_notes.html)), if you're on Heroku you should use their [env vars configuration](https://devcenter.heroku.com/articles/config-vars).  Also, I really like the the [dotenv-rails](https://github.com/bkeepers/dotenv) gem (for development only).  There are many ways to do this, but as you highlighted, one should never commit sensitive env vars to their repo.
