### ISSUE TITLE
No events API to create own UI elements & JS listeners

### ISSUE THREAD

**Issue by andypandy** [kjohnston/s3_relay#6]
**Proposed events (and parameters) to implement:**
-Batch upload started (list  of files)
-Batch progress (progress)
-Batch upload finished (files[errors])
-File upload started (file)
-File upload progress (file[progress])
-File upload finished (file)
-File error (file[error details])

**Backwards compatibility**
Gem needs backwards compatibility with existing implementations so I was going to leave the existing UI elements in as overwriteable defaults that use the new events API

**Comment by kjohnston** [comment]
Regarding backwards compatibility, I'm interested in @bousquet and @djohnson's input.  I feel like the first round of apps could pin to a final gem release including the success-event branch.  Then we can jump up a minor version for the new round of apps, thus preventing the need to maintain legacy markup.

**Comment by bousquet** [comment]
I'm ok with creating a release tag for current functionality.

**Comment by andypandy** [comment]
So I'll remove all UI elements for the next "minor version", and I'll do this last so we have all the other improvements in it (retry/queuing, decoupling from parent record, etc)

**Comment by kjohnston** [comment]
Any objections to this?

* Merge the success-event branch and release version 0.1.1 of the gem
  * Existing apps can use "~> 0.1.1"
* Master can proceed with breaking changes until version 0.2.0 is released

**Comment by djohnson** [comment]
Regarding backwards compatibility and the future of the gem: I think it's important for the gem to maintain at least a basic UI that is customizable or overridable.  The majority of projects that have used this gem so far have had a UI element so I think it's safe to say it's the standard use case.  Also, as a new user coming into a library like this you really need a starting off point to that you can get modifying to fit your needs without first needing to reinvent the wheel.  I think moving forward we can update the UI as needed, but some basic structure should remain.  

@kjohnston do you have any objection to including my PR in the next release?  It's backwards compatible.  Either way, if we include success-event in the next release it should be 0.2.0 as it includes new functionality.
