### ISSUE TITLE
Rails 5 Deprecation warning 

### ISSUE THREAD

**Issue by mfpiccolo** [kjohnston/s3_relay#9]
I am getting a the following warning:

DEPRECATION WARNING: Passing string to define callback is deprecated and will be removed in Rails 5.1 without replacement. (called from s3_relay at /Users/mfpiccolo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/s3_relay-1b7710f12867/lib/s3_relay/model.rb:40)

**Comment by kjohnston** [comment]
@mfpiccolo thanks for opening.  This should be addressable by changing `association_method ` to `association_method.to_sym` [here](https://github.com/kjohnston/s3_relay/blob/master/lib/s3_relay/model.rb#L40).  Since you've got a Rails 5 app in front of you would you mind taking a swing at it?

**Comment by mfpiccolo** [comment]
Just update Gemini to Rails 5 man. :trollface: 

Yeah I can take it.

**Comment by kjohnston** [comment]
Closed via #10
